# deploy/values.yaml

# Доменное имя, которое будет торчать наружу
domain: demo.kailas.cloud

# Настройки деплоймента
replicaCount: 1

image:
  repository: harbor.kailas.cloud/demo/kailas-demo
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-demo-regcred

# Минимальный ingress под Nginx + cert-manager + external-dns
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: demo.kailas.cloud
  hosts:
    - host: demo.kailas.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: demo-kailas-cloud-tls
      hosts:
        - demo.kailas.cloud

resources: {}

fullnameOverride: kailas-demo
