name: Release & deploy to kailas

on:
  push:
    tags:
      - "v*.*.*"   # v1.0.0, v0.1.3 и т.п.

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}     # owner/repo
  IMAGE_TAG: ${{ github.ref_name }}        # v1.2.3
  KUSTOMIZE_DIR: k8s
  # имя образа из kustomization.yaml, слева от =
  # например если там "images: - name: ghcr.io/owner/repo"
  KUSTOMIZE_IMAGE_NAME: ghcr.io/${{ github.repository }}

permissions:
  contents: write      # чтобы создать релиз
  packages: write

jobs:
  release-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.IMAGE_TAG }}
          name: Release ${{ env.IMAGE_TAG }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.32.0"

      - name: Setup kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "5.4.2"

      - name: Write kubeconfig
        run: |
          echo "${{ secrets.K8S_CONFIG_B64 }}" | base64 --decode > kubeconfig
          chmod 600 kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Set image tag in kustomize
        working-directory: ${{ env.KUSTOMIZE_DIR }}
        run: |
          kustomize edit set image \
            ${{ env.KUSTOMIZE_IMAGE_NAME }}=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Apply kustomization
        working-directory: ${{ env.KUSTOMIZE_DIR }}
        run: |
          kustomize build . | kubectl apply -f -
